apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcha-webapp-dev
spec:
  selector:
    matchLabels:
      run: watcha-webapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: watcha-webapp
    spec:
      containers:
      - name: watcha-webapp
        image: jeg910716/watcha-webapp:dev
        ports:
        - containerPort: 80