apiVersion: apps/v1
kind: Deployment
metadata:
  name: labda-webapp
spec:
  selector:
    matchLabels:
      run: labda-webapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: labda-webapp
    spec:
      containers:
      - name: labda-webapp
        image: jeg910716/labda-webapp
        ports:
        - containerPort: 80
---	
apiVersion: v1	
kind: Service	
metadata:	
  name: labda-webapp
  labels:	
    run: labda-webapp	
spec:	
  selector:	
    run: labda-webapp	
  ports:	
  - port: 3010
    targetPort: 3000	
    protocol: TCP	
  type: LoadBalancer 